" /etc/vim/vimrc

" For compat with the Vim-related packages available in Debian
runtime! debian.vim

syntax on
set background=dark	" Dark mode
set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
set ignorecase		" Do case insensitive matching
set smartcase		" Do smart case matching
set incsearch		" Incremental search
set autoread		" Reload buf if file changed on disk
set autowrite		" Automatically save before commands like :next and :make
set hidden		" Hide buffers when they are abandoned
set mouse=a		" Enable mouse usage (all modes)
set autoindent		" Basic, compat with filetype-based indent below
set shiftwidth=2	" Indent by 2 spaces

" Hotkey to put current ISO8601 time in paste register
nnoremap <F5> "=strftime("%FT%T%z")<CR>

" Filetype-based auto-indentation
if has("autocmd")
  filetype plugin indent on
endif

" Save last-used position in file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

